apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagramcluster
  region: us-east-1

kubernetesNetworkConfig:
  serviceIPv4CIDR: 10.0.0.0/16

vpc:
  clusterEndpoints:
    publicAccess: true

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80