version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: nafiou18/reverseproxy:1.2
  backend_user:
    build:
      context: ./udagram-api-user
    image: nafiou18/udagram-api-user:1.1
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: nafiou18/udagram-api-feed:1.3
  frontend:
    build:
      context: ./udagram-frontend
    image: nafiou18/udagram-frontend:v3
