name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.DOCKER_USERNAME }}
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker --version
      run: docker-compose -f docker-compose-build.yaml build --parallel
    - name: push images
      run: |
        docker push nafiou18/reverseproxy:1.2
        docker push nafiou18/udagram-api-user:1.0
        docker push nafiou18/udagram-api-feed:1.0
        docker push nafiou18/udagram-frontend:v2
    
