name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: docker --version
      run: docker-compose -f ../docker-compose-build.yaml build --parallel
    - name: push images
      run: | 
        echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
        docker push nafiou18/reverseproxy:1.0
        docker push nafiou18/udagram-api-user:1.0
        docker push nafiou18/udagram-api-feed:1.0
        docker push nafiou18/udagram-frontend:1.0
    
